name: Build music index

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate index.json
        run: |
          node ./scripts/build_index.js
      - name: Commit index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update index.json"
          file_pattern: index.json
